import { ToastContainer } from "react-toastify";
import "./globals.css";
import { HeroUIProvider } from "@heroui/react";
import SessionWrapper from "./components/SessionWrapper/page";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <SessionWrapper>
          <HeroUIProvider>{children}</HeroUIProvider>
          <ToastContainer />
        </SessionWrapper>
      </body>
    </html>
  );
}
