import { HeroUIProvider } from "@heroui/system";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <HeroUIProvider>
        {children}
        </HeroUIProvider>
      </body>
    </html>
  );
}
